img_dir: data/aug_images-flouro
mask_dir: data/aug_masks-flouro
grayscale: false
augment: true
checkpoint: checkpoints/fluoro.pt
batch_size: 10
num_epochs: 15
lr: 1e-3
weight_decay: 1e-5
calculate_weights: false

