img_dir: data/aug_images-nonfluoro
mask_dir: data/aug_masks-nonfluoro
grayscale: false
augment: true
checkpoint_folder: checkpoints
checkpoint: non_flouro.pt
batch_size: 10
num_epochs: 15
lr: 1e-3
weight_decay: 1e-5
calculate_weights: false

